### ISSUE TITLE
Privacy manifest required by Apple

### ISSUE THREAD

**Issue by wenfeng-duan** [giginet/Crossroad#49]
Hi team,

Starting with Spring 2024 Apple requires third-party SDKs to add a Privacy Manifest file.
https://developer.apple.com/support/third-party-SDK-requirements/
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

Does this SDK need a privacy manifest? If yes, is there any plans to add a privacy manifest?

Thanks,
Duan

**Comment by giginet** [comment]
Hi.

Crossroad doesn't track any user events. 
Also, any "reason required APIs" are not used, such as file systems or UserDefaults.

In my understanding, we don't have to prepare the Privacy Manifest in this case. 
Could you tell me your any other concerns?

**Comment by giginet** [comment]
Here is the discussion on the Apple Developer forum.

According to this, if libraries don't use any required APIs, they needn't add privacy manifests.

So I plan to do nothing for Crossroad.
https://developer.apple.com/forums/thread/746481?answerId=782256022#782256022
