### ISSUE TITLE
Archiving latest release.

### ISSUE THREAD

**Issue by ghost** [giginet/Crossroad#7]
Hi,

Would you mind performing the Carthage [archive](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file) function on [this release](https://github.com/giginet/Crossroad/releases/tag/1.0.1) please?

### Steps
1. checkout the release 
2. run the following commands
3. select `edit` on the tagged GitHub [release]((https://github.com/giginet/Crossroad/releases/tag/1.0.1))

```bash
carthage build --no-skip-current
carthage archive Crossroad
```

**Comment by giginet** [comment]
Hi!

Umm. I tried this operation on Carthage 0.30.1. Then it would be success.
Could you tell me your environment?

```
 Crossroad (f8b650e) ● carthage archive Crossroad
Could not find any copies of Crossroad.framework. Make sure you're in the project's root and that the frameworks have already been built using 'carthage build --no-skip-current'.
 Crossroad (f8b650e) ● carthage build --no-skip-current
*** xcodebuild output can be found in /var/folders/j7/v8p66lxs6rscf8j41x6f19g80000gn/T/carthage-xcodebuild.k36m03.log
*** Building scheme "Crossroad" in Crossroad.xcodeproj
 Crossroad (f8b650e) ● carthage archive Crossroad
*** Found Carthage/Build/iOS/Crossroad.framework
*** Found Carthage/Build/iOS/Crossroad.framework.dSYM
*** Found Carthage/Build/iOS/68883DB3-DCD2-3990-A344-309144419671.bcsymbolmap
*** Found Carthage/Build/iOS/2A966C1E-F37B-33D1-A227-5B5D6DABDF4B.bcsymbolmap
*** Found Carthage/Build/iOS/557221AC-C5CF-3689-8F51-98469938539E.bcsymbolmap
*** Found Carthage/Build/iOS/D19E8A90-0B44-3FA1-A9F6-D10CB6401692.bcsymbolmap
*** Created Crossroad.framework.zip

```

**Comment by ghost** [comment]
It is a success?

**Comment by ghost** [comment]
Edit the release and add `Crossroad.framework.zip`

**Comment by giginet** [comment]
It works.
Could you tell me more detail?
(outputs or your carthage version etc...)

**Comment by ghost** [comment]
I get the same output as you. The file `Crossroad.framework.zip` has been created.

Now append that file in your release (where you see this)

<img width="780" alt="screen shot 2018-07-09 at 15 28 22" src="https://user-images.githubusercontent.com/14126999/42456428-d048e840-838c-11e8-8cc3-18cf5ff7e8af.png">

**Comment by giginet** [comment]
I got. I added

**Comment by ghost** [comment]
Thanks
