### ISSUE TITLE
logo design Proposal 

### ISSUE THREAD

**Issue by Arslanshn** [giginet/Crossroad#8]
Hello! I want to contribute on your project with making logo design. What do you think about it?

Best Regards,
Arslan Şahin
Graphics Designer

**Comment by giginet** [comment]
That would be great!!! 👍 

This library is an URL router. So I named from crossroad. (or traffic sign)
I defer your inspiration by this name.

**Comment by Arslanshn** [comment]
https://drive.google.com/open?id=1TfaFxpVYxld64erTgB0D50x16VJybqSV
hello I did the logo work I hope you like:)

**Comment by giginet** [comment]
Great job @Arslanshn !
I can't believe such a cool log!  :blush:

I submitted #9 . I have a question for you about license.
Could you comment to #9?

**Comment by giginet** [comment]
@Arslanshn Thank you for everything!

I donated tip to your BTC wallet.
This isn't much, but please buy 🍻 .
